export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const TEMP_CHANGED = "TEMP_CHANGED";
export const TEMP_DATA_RECEIVED = 'TEMP_DATA_RECEIVED';
export const START_POLLING = 'START_POLLING';
export const STOP_POLLING = 'STOP_POLLING';